In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (10, 6)

from sklearn import datasets

## Задание 1
### Загрузка DataFrame

In [29]:
column_names = ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm', 'class']
iris = pd.read_csv("data/iris/iris.data", names=column_names)
print("Начало датасета ирисов")
iris.head()

Начало датасета ирисов

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

### Нахождение корреляций

In [30]:
print("Общая корреляция ирисов")
iris.corr(numeric_only=True)

Общая корреляция ирисов

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm
sepal_length_cm,1.000000,-0.109369,0.871754,0.817954
sepal_width_cm,-0.109369,1.000000,-0.420516,-0.356544
petal_length_cm,0.871754,-0.420516,1.000000,0.962757
petal_width_cm,0.817954,-0.356544,0.962757,1.000000

In [31]:
print("Сгруппированная корреляция по классам ирисов")
iris.groupby("class").corr(numeric_only=True)

Сгруппированная корреляция по классам ирисов

                                 sepal_length_cm  sepal_width_cm  \
class
Iris-setosa     sepal_length_cm         1.000000        0.746780
                sepal_width_cm          0.746780        1.000000
                petal_length_cm         0.263874        0.176695
                petal_width_cm          0.279092        0.279973
Iris-versicolor sepal_length_cm         1.000000        0.525911
                sepal_width_cm          0.525911        1.000000
                petal_length_cm         0.754049        0.560522
                petal_width_cm          0.546461        0.663999
Iris-virginica  sepal_length_cm         1.000000        0.457228
                sepal_width_cm          0.457228        1.000000
                petal_length_cm         0.864225        0.401045
                petal_width_cm          0.281108        0.537728

                                 petal_length_cm  petal_width_cm
class
Iris-setosa     sepal_length_cm         0.263874        0.279092
                sepal_width_cm          0.176695        0.279973
                petal_length_cm         1.000000        0.306308
                petal_width_cm          0.306308        1.000000
Iris-versicolor sepal_length_cm         0.754049        0.546461
                sepal_width_cm          0.560522        0.663999
                petal_length_cm         1.000000        0.786668
                petal_width_cm          0.786668        1.000000
Iris-virginica  sepal_length_cm         0.864225        0.281108
                sepal_width_cm          0.401045        0.537728
                petal_length_cm         1.000000        0.322108
                petal_width_cm          0.322108        1.000000